from factory.pipelines.pipeline import MetaPipeline
from factory.connectors.connectors import KafkaConnector
from factory import settings
import asyncio
import random

class StreamPipeline(metaclass=MetaPipeline):
    '''stream pipeline is for transfer results after middleware chain or logger
       all generated by the factory information should pass this pipeline
    '''
    def __init__(self):
        pass

    @staticmethod
    async def generate_whatever():
        while True:
            yield {'mock': random.randrange(0, 1000)}
            await asyncio.sleep(0.1)


    async def start(self):
        pass


class KafkaStreamPipeline(StreamPipeline):

    def __init__(self):
        super().__init__()

    async def start(self, topic, queue):
        self.pipeline = KafkaConnector(topic)
        self.stream_queue = queue
        await self.pipeline.start_producer()

    async def emit(self, msg):
        await self.start()
        for send_msg in msg:
            await self.pipeline.producer.send(settings.STREAM_TOPIC, value=send_msg)
            await self.pipeline.producer.flush()